name: Lectionary API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true
          
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag us.gcr.io/${{ secrets.GCLOUD_PROJECT }}/lectionary:$(git rev-parse --short HEAD) --target prod

      - name: Configure Docker to use Google Cloud Platform
        run: "gcloud auth configure-docker --quiet"

      - name: Push image to Google Cloud Container Registry
        run: "docker push us.gcr.io/${{ secrets.GCLOUD_PROJECT }}/lectionary:$(git rev-parse --short HEAD)"

      - name: Install beta commands and deploy on cloud run
        run: "gcloud components install beta --quiet && gcloud beta run deploy lectionary --image us.gcr.io/${{ secrets.GCLOUD_PROJECT }}/lectionary:$(git rev-parse --short HEAD) --project ${{ secrets.GCLOUD_PROJECT }} --region us-east1 --platform managed"
